config/routes.rb
Rails.application.routes.draw do
  resources :qand_as
  resources :surveys
  resources :posts
  resources :messages
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/qand_a.rb
class QandA
  include Mongoid::Document
  field :qa, type: String
end

app/controllers/qand_as_controller.rb
class QandAsController < ApplicationController
  before_action :set_qand_a, only: [:show, :edit, :update, :destroy]

  # GET /qand_as
  # GET /qand_as.json
  def index
    @qand_as = QandA.all
  end

  # GET /qand_as/1
  # GET /qand_as/1.json
  def show
  end

  # GET /qand_as/new
  def new
    @qand_a = QandA.new
  end

  # GET /qand_as/1/edit
  def edit
  end

  # POST /qand_as
  # POST /qand_as.json
  def create
    @qand_a = QandA.new(qand_a_params)

    respond_to do |format|
      if @qand_a.save
        format.html { redirect_to @qand_a, notice: 'Qand a was successfully created.' }
        format.json { render :show, status: :created, location: @qand_a }
      else
        format.html { render :new }
        format.json { render json: @qand_a.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /qand_as/1
  # PATCH/PUT /qand_as/1.json
  def update
    respond_to do |format|
      if @qand_a.update(qand_a_params)
        format.html { redirect_to @qand_a, notice: 'Qand a was successfully updated.' }
        format.json { render :show, status: :ok, location: @qand_a }
      else
        format.html { render :edit }
        format.json { render json: @qand_a.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /qand_as/1
  # DELETE /qand_as/1.json
  def destroy
    @qand_a.destroy
    respond_to do |format|
      format.html { redirect_to qand_as_url, notice: 'Qand a was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_qand_a
      @qand_a = QandA.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def qand_a_params
      params.require(:qand_a).permit(:qa)
    end
end

app/helpers/qand_as_helper.rb
module QandAsHelper
end

app/views/qand_as/_form.html.erb
<%= form_with(model: qand_a, local: true) do |form| %>
  <% if qand_a.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(qand_a.errors.count, "error") %> prohibited this qand_a from being saved:</h2>

      <ul>
      <% qand_a.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :qa %>
    <%= form.text_field :qa, id: :qand_a_qa %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/qand_as/edit.html.erb
<h1>Editing Qand A</h1>

<%= render 'form', qand_a: @qand_a %>

<%= link_to 'Show', @qand_a %> |
<%= link_to 'Back', qand_as_path %>

app/views/qand_as/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Qand As</h1>

<table>
  <thead>
    <tr>
      <th>Qa</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @qand_as.each do |qand_a| %>
      <tr>
        <td><%= qand_a.qa %></td>
        <td><%= link_to 'Show', qand_a %></td>
        <td><%= link_to 'Edit', edit_qand_a_path(qand_a) %></td>
        <td><%= link_to 'Destroy', qand_a, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Qand A', new_qand_a_path %>

app/views/qand_as/new.html.erb
<h1>New Qand A</h1>

<%= render 'form', qand_a: @qand_a %>

<%= link_to 'Back', qand_as_path %>

app/views/qand_as/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Qa:</strong>
  <%= @qand_a.qa %>
</p>

<%= link_to 'Edit', edit_qand_a_path(@qand_a) %> |
<%= link_to 'Back', qand_as_path %>